type: l3leaf

l3leaf:

  defaults:
    platform: vEOS-LAB
    # node BGP AS
    bgp_as: 65100
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    loopback_ipv4_pool: 10.200.1.0/24
    # Enable / Disable auto MLAG, when two nodes are defined in node group.
    mlag: true
    mlag_interfaces: [Ethernet12, Ethernet13]
    # Underlay L3 peering SVI interface id
    # If set to false or the same vlan as mlag_peer_vlan the mlag_peer_vlan will be used for L3 peering.
    mlag_peer_l3_vlan: 4093
    # MLAG Peer Link (control link) SVI interface id
    mlag_peer_vlan: 4094
    # IP address pool used for MLAG Peer Link (control link)
    # IP is derived from the node id.
    mlag_peer_ipv4_pool: 10.255.252.0/24
    # IP address pool used for MLAG underlay L3 peering
    # IP is derived from the node id.
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    # IPv4 subnet to use to connect to uplink switches.
    uplink_ipv4_pool: 172.31.255.0/24
    # Local uplink interfaces (list).
    uplink_interfaces: ['Ethernet1', 'Ethernet2']
    # Uplink switches (list).
    uplink_switches: ['BC-SPINE1', 'BC-SPINE2']
    # Spanning-tree defaults
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address : 00:dc:00:00:00:0a
  node_groups:
    BC_BORDER_RACK1:
      bgp_as: 65101
      filter:
        tenants: [BC_BLUE, BC_RED]
        tags: [vmotion, nfs]
      nodes:
        BC-BORDERLEAF1:
          id: 1
          mgmt_ip: 172.20.21.101/23
          uplink_switch_interfaces: [Ethernet1, Ethernet1]

        BC-BORDERLEAF2:
          id: 2
          mgmt_ip: 172.20.21.102/23
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    BC_DATA_RACK2:
      bgp_as: 65102
      filter:
        tenants: [BC_BLUE, BC_RED]
        tags: [vmotion, nfs, blue_zone, red_zone]
      nodes:
        BC-DATALEAF3:
          id: 3
          mgmt_ip: 172.20.21.103/23
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        BC-DATALEAF4:
          id: 4
          mgmt_ip: 172.20.21.104/23
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
    BC_DATA_RACK3:
      bgp_as: 65103
      filter:
        tenants: [BC_BLUE, BC_RED]
        tags: [vmotion, nfs, blue_zone, red_zone]
      nodes:
        BC-DATALEAF5:
          id: 5
          mgmt_ip: 172.20.21.105/23
          uplink_switch_interfaces: [Ethernet5, Ethernet5]
        BC-DATALEAF6:
          id: 6
          mgmt_ip: 172.20.21.106/23
          uplink_switch_interfaces: [Ethernet6, Ethernet6]
    BC_STO_RACK1:
      bgp_as: 65104
      filter:
        tenants: [BC_STO]
        tags: [vmotion, nfs, sto_zone]
      nodes:
        BC-STOLEAF1:
          id: 7
          mgmt_ip: 172.20.21.111/23
          uplink_switch_interfaces: [Ethernet7, Ethernet7]
        BC-STOLEAF2:
          id: 8
          mgmt_ip: 172.20.21.112/23
          uplink_switch_interfaces: [Ethernet8, Ethernet8]
    BC_STO_RACK2:
      bgp_as: 65105
      filter:
        tenants: [BC_BLUE, BC_STO]
        tags: [vmotion, nfs, blue_zone_a_1, sto_zone]
      nodes:
        BC-STOLEAF3:
          id: 9
          mgmt_ip: 172.20.21.113/23
          uplink_switch_interfaces: [Ethernet9, Ethernet9]
        BC-STOLEAF4:
          id: 10
          mgmt_ip: 172.20.21.114/23
          uplink_switch_interfaces: [Ethernet10, Ethernet10]

leaf_bgp_defaults:
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart