---
bc_servers_rack4:

  storage_server_1:
    rack: R4                                         #This is used for Documentation
    adapters:
      - endpoint_ports: [ Eth3, Eth4 ]                   #this field are for the interfaces on the server side used in Interface Description [Port1->switchA, Port2->switchB]
        switch_ports: [ Ethernet3, Ethernet3 ]     #this is to identify the switch ports that are used to connect to the server [switchA, switchB]
        switches: [ BC-STOLEAF1, BC-STOLEAF2 ]       #this is to identify on which switches to apply this configuration
        profile: storage_server_zoneA
        port_channel:                                    #port channel definintions Port channel number is auto-derived from switch port# ie po481 = eth48/1
          state: present
          description: portchannel-storage_zoneA            #description of port-channel, applied to both switches
          mode: active                                   #active/passive/on
          #additional fields such as lacp_fallback can be found on avd.sh under connected-endpoints
      - endpoint_ports: [ Eth5, Eth6 ]                   #this field are for the interfaces on the server side used in Interface Description [Port1->switchA, Port2->switchB]
        switch_ports: [ Ethernet4, Ethernet4 ]     #this is to identify the switch ports that are used to connect to the server [switchA, switchB]
        switches: [ BC-STOLEAF1, BC-STOLEAF2 ]       #this is to identify on which switches to apply this configuration
        profile: storage_server_zoneb
        port_channel:                                    #port channel definintions Port channel number is auto-derived from switch port# ie po481 = eth48/1
          state: present
          description: portchannel-storage_zoneB            #description of port-channel, applied to both switches
          mode: active                                   #active/passive/on
          #additional fields such as lacp_fallback can be found on avd.sh under connected-endpoints

  storage_server_2:
    rack: R4                                         #This is used for Documentation
    adapters:
      - endpoint_ports: [ Eth3, Eth4 ]                   #this field are for the interfaces on the server side used in Interface Description [Port1->switchA, Port2->switchB]
        switch_ports: [ Ethernet5, Ethernet5 ]     #this is to identify the switch ports that are used to connect to the server [switchA, switchB]
        switches: [ BC-STOLEAF1, BC-STOLEAF2 ]       #this is to identify on which switches to apply this configuration
        profile: storage_server_zoneA
        port_channel:                                    #port channel definintions Port channel number is auto-derived from switch port# ie po481 = eth48/1
          state: present
          description: portchannel-storage_zoneA            #description of port-channel, applied to both switches
          mode: active                                   #active/passive/on
          #additional fields such as lacp_fallback can be found on avd.sh under connected-endpoints
      - endpoint_ports: [ Eth5, Eth6 ]                   #this field are for the interfaces on the server side used in Interface Description [Port1->switchA, Port2->switchB]
        switch_ports: [ Ethernet6, Ethernet6 ]     #this is to identify the switch ports that are used to connect to the server [switchA, switchB]
        switches: [ BC-STOLEAF1, BC-STOLEAF2 ]       #this is to identify on which switches to apply this configuration
        profile: storage_server_zoneb
        port_channel:                                    #port channel definintions Port channel number is auto-derived from switch port# ie po481 = eth48/1
          state: present
          description: portchannel-storage_zoneB            #description of port-channel, applied to both switches
          mode: active                                   #active/passive/on
          #additional fields such as lacp_fallback can be found on avd.sh under connected-endpoints