
ansible_connection: httpapi
ansible_network_os: eos
ansible_user: cvpadmin
# should use vault for passwords
#ansible_ssh_pass: xxx
ansible_become: true
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
# Configuration to get Virtual Env information
ansible_python_interpreter: $(which python3)
