###################################################################
## BC Information Technology Specific Information - VRFs / VLANs ##
###################################################################

BC_BLUE:
  mac_vrf_vni_base: 10000
  vrfs:
    BC_BLUE_ZONE_A:
      vrf_vni: 10
      vtep_diagnostic:
        loopback: 100
        loopback_ip_range: 10.255.1.0/24
      svis:
        110:
          name: BC_BLUE_ZONE_A_1
          tags: [blue_zone, blue_zone_a_1]
          enabled: true
          ip_address_virtual: 10.1.10.1/24
          structured_config:
            access_group_in: "leaf_acl"
        111:
          name: BC_BLUE_ZONE_A_2
          tags: [blue_zone, blue_zone_a_2]
          enabled: true
          ip_address_virtual: 10.1.11.1/24

        112:
          name: BC_BLUE_ZONE_A_3
          tags: [blue_zone, blue_zone_a_3]
          enabled: true
          ip_address_virtual: 10.1.12.1/24
    BC_BLUE_ZONE_B:
      vrf_vni: 11
      svis:
        120:
          name: BC_BLUE_ZONE_B_1
          tags: [blue_zone, blue_zone_b_1]
          enabled: true
          ip_address_virtual: 10.1.20.1/24
        121:
          name: BC_BLUE_ZONE_B_2
          tags: [blue_zone, blue_zone_b_2]
          enabled: true
          ip_address_virtual: 10.1.21.1/24

  l2vlans:
    160:
      vni_override: 50160
      name: BC_VMOTION
      tags: [vmotion]
    161:
       name: BC_NFS
       tags: [nfs]